# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
  # - 1.5 TODO: add back in
  - nightly

env:
  jobs:
    # - USE_CONDA=true
    - USE_CONDA=false
matrix:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      before_script:
        - if [ -z "$DOCUMENTER_KEY" ]; then echo "cannot find DOCUMENTER_KEY"; fi

        # Install R
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --allow-unauthenticated git r-base r-base-dev r-recommended -y; fi
      # - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo R -e 'install.packages("ggplot2", dep=TRUE, repos="http://cran.us.r-project.org")'; fi # takes ~ 6min 2018-06-02
      after_success: skip
notifications:
  email: false
codecov: true

before_install:
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ] ; then sudo apt-get install --allow-unauthenticated git r-base r-base-dev r-recommended -y; fi

  # osx
  # faster than using homebrew/science tap
  # but no permalink to release download
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$USE_CONDA" == "false" ]; then wget "https://cran.rstudio.com/bin/macosx/$(wget -qO- https://cran.rstudio.com/bin/macosx/ | sed -n 's/.*href="\(R-[^"]*.pkg\)".*/\1/p' | head -n 1)"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$USE_CONDA" == "false" ]; then sudo installer -pkg R-*.pkg -target /; fi

  - java -version
  - ls
  - Rscript install_r.R
  # - R_HOME=$(R RHOME)
  # - echo $R_HOME


