# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
codecov: true

before_install:
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ] ; then sudo apt-get install --allow-unauthenticated git r-base r-base-dev r-recommended -y; fi

  # osx
  # faster than using homebrew/science tap
  # but no permalink to release download
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$USE_CONDA" == "false" ]; then wget "https://cran.rstudio.com/bin/macosx/$(wget -qO- https://cran.rstudio.com/bin/macosx/ | sed -n 's/.*href="\(R-[^"]*.pkg\)".*/\1/p' | head -n 1)"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$USE_CONDA" == "false" ]; then sudo installer -pkg R-*.pkg -target /; fi

  - echo $R_HOME
  - echo TEST
  - R_HOME=$(R RHOME)
  - echo $R_HOME


jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip